version: "3.8"
services:
  spring-boot-app:
    container_name: spring-boot-app
    build: .
    restart: always
    ports:
      - "9091:9090"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/quiz_db?verifyServerCertificate=false&useSSL=false&requireSSL=false
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
  mysqldb:
    container_name: mysqldb
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=quiz_db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      springboot-mysql-net:

networks:
  springboot-mysql-net:


